name: Thing

on: [push]

jobs:
  julia:
    runs-on: ubuntu-18.04
    container: docker://julia:1.3
    steps:
    - uses: actions/checkout@v2
    - run: if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - run: julia --project -e 'using Pkg; Pkg.test("Dionysus"; coverage=true)'
