name: Thing

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: docker://continuumio/miniconda3:4.7.12
    - run: conda install -q -y -c conda-forge numpy
    - run: source $CONDA/bin/activate base
    - run: echo $(pwd -P)
    - run: echo $(ls -gGAh)
    - uses: actions/checkout@v1
    - run: echo $(ls -gGAh)
    - run: python pythonthings.py
