name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - run: if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - uses: docker://julia:1.2
    - run: using Pkg
    - run: Pkg.activate .
    - run: Pkg.test("Dionysus"; coverage=true)
    - uses: docker://julia:latest
    - run: julia --project -e 'using Pkg; Pkg.test("Dionysus"; coverage=true)'
